[profile.ci.fuzz]
runs = 10_000

[profile.default]
solc = "0.8.20"
optimizer = true
optimizer_runs = 1_000
via_ir = true
bytecode_hash = "none"

[rpc_endpoints]
real = "${REAL_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum_one = "${ARBITRUM_RPC_URL}"

unreal = "${UNREAL_RPC_URL}"
polygon_mumbai = "${MUMBAI_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum_one_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
sepolia = { key = "${ETHERSCAN_MAINNET_KEY}" }
polygon = { key = "${ETHERSCAN_POLYGON_KEY}" }
mumbai = { key = "${ETHERSCAN_POLYGON_KEY}" }
# real = { key = "${ETHERSCAN_REAL_KEY}", url = "https://real.blockscout.com/api" }
unreal = { key = "", url = "https://unreal.blockscout.com/api" }
arbitrum_one_sepolia = { key = "${ETHERSCAN_ARBITRUM_KEY}", url="https://api-sepolia.arbiscan.io/api" }

[fmt]
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
