[profile.ci.fuzz]
runs = 10_000

[profile.default]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.optimized]
optimizer_runs = 10_000
via_ir = true
bytecode_hash = "none"

[rpc_endpoints]
real = "${REAL_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum_one = "${ARBITRUM_RPC_URL}"

unreal = "${UNREAL_RPC_URL}"
polygon_mumbai = "${MUMBAI_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }

[fmt]
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
